FROM node:18-buster-slim
LABEL org.opencontainers.image.source="https://github.com/Nikki18977/0201_angular"

ENV NG_CLI_ANALYTICS="false"
ENV PATH=$PATH:/app/node_modules/.bin/ 

WORKDIR /app
COPY . .

RUN npm install

CMD ["npm", "run", "lint"]
