FROM node:18-buster-slim
LABEL org.opencontainers.image.source="https://github.com/Nikki18977/0201_angular"

ENV NG_CLI_ANALYTICS="false"
ENV PATH=$PATH:/app/node_modules/.bin/ 

WORKDIR /app
COPY . .
RUN npm install 

RUN apt-get update &&\
    apt-get install -y wget &&\
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&\
    apt-get -y install ./google-chrome-stable_current_amd64.deb 

CMD ["npm", "test"]

